# Generated by Django 6.0.4 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zasob',
            name='status',
            field=models.CharField(default='Available', max_length=100),
        ),
        migrations.AlterModelTable(
            name='zasob',
            table='zasob',
        ),
    ]
