# Generated by Django 6.0.4 on 2026-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_zasob_status_alter_zasob_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='zasob',
            name='lat',
            field=models.FloatField(default=51.1079),
        ),
        migrations.AddField(
            model_name='zasob',
            name='lng',
            field=models.FloatField(default=17.0385),
        ),
        migrations.AlterField(
            model_name='zasob',
            name='id',
            field=models.AutoField(db_column='id_zasobu', primary_key=True, serialize=False),
        ),
    ]
