# Generated by Django 6.0.4 on 2026-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_incydent_data_zgloszenia_notatki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incydent',
            name='typ',
            field=models.CharField(choices=[('Road Incident', 'Road Incident'), ('Medical Emergency', 'Medical Emergency'), ('Public Order Disturbance', 'Public Order Disturbance'), ('Domestic Violence', 'Domestic Violence'), ('Fire', 'Fire'), ('Technical & Weather Hazard', 'Technical & Weather Hazard'), ('Intoxicated or Dangerous Person', 'Intoxicated or Dangerous Person'), ('Theft & Suspicious Activity', 'Theft & Suspicious Activity'), ('Animal Assistance', 'Animal Assistance'), ('Missing Person', 'Missing Person'), ('Other', 'Other')], max_length=50),
        ),
    ]
